<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Error while attacking a player</title>
    <link>https://forum.moparisthebest.com/t/error-while-attacking-a-player/258587</link>
    <description>guys idk what happened but now after few attacking turns the attacker gets this ang get dced:
[code]
[client-1-Brutal k0]: Loading Process Completed  [Has powers, lag: 0 ms]
Error with player 1, Brutal k0
java.lang.ArrayIndexOutOfBoundsException: -1
        at client.rangeGFXNPC(client.java:2991)
        at client.Attack(client.java:6272)
        at client.process(client.java:17019)
        at PlayerHandler.process(PlayerHandler.java:270)
        at process.run(process.java:23)
        at java.lang.Thread.run(Unknown Source)
Game saved for player Brutal k0
ClientHandler: Client Brutal k0 disconnected (localhost)
Connection from localhost:2319
[client-1-Brutal k0]: Loading Process Completed  [Has powers, lag: 16 ms]
[/code]
any 1 have any idea of what is happening?</description>
    
    <lastBuildDate>Mon, 26 Jan 2009 13:01:30 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/error-while-attacking-a-player/258587.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Error while attacking a player</title>
        <dc:creator><![CDATA[@moparclient moparclient]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/moparclient">@moparclient</a> wrote:</p>
          <blockquote>
              <p>guys idk what happened but now after few attacking turns the attacker gets this ang get dced:</p>
<pre><code class="lang-auto">[client-1-Brutal k0]: Loading Process Completed  [Has powers, lag: 0 ms]
Error with player 1, Brutal k0
java.lang.ArrayIndexOutOfBoundsException: -1
        at client.rangeGFXNPC(client.java:2991)
        at client.Attack(client.java:6272)
        at client.process(client.java:17019)
        at PlayerHandler.process(PlayerHandler.java:270)
        at process.run(process.java:23)
        at java.lang.Thread.run(Unknown Source)
Game saved for player Brutal k0
ClientHandler: Client Brutal k0 disconnected (localhost)
Connection from localhost:2319
[client-1-Brutal k0]: Loading Process Completed  [Has powers, lag: 16 ms]</code></pre>
<p>any 1 have any idea of what is happening?</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/error-while-attacking-a-player/258587/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/error-while-attacking-a-player/258587/1</link>
        <pubDate>Mon, 26 Jan 2009 13:01:30 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-258587-1</guid>
        <source url="https://forum.moparisthebest.com/t/error-while-attacking-a-player/258587.rss">Error while attacking a player</source>
      </item>
  </channel>
</rss>
