<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Can somebody please help me on this error</title>
    <link>https://forum.moparisthebest.com/t/can-somebody-please-help-me-on-this-error/220669</link>
    <description>I was running the 474 server than the client,than this error came up when i logged on with d00m
[code]16/07/2008 17:45:21 com.mchange.v2.log.MLog &lt;clinit&gt;
INFO: MLog clients using java 1.4+ standard logging.
16/07/2008 17:45:22 com.mchange.v2.c3p0.C3P0Registry banner
INFO: Initializing c3p0-0.9.1.1 [built 15-March-2007 01:32:31; debug? true; trac
e: 10]
16/07/2008 17:45:22 com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource getPoo
lManager
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@22d9f7a
5 [ connectionPoolDataSource -&gt; com.mchange.v2.c3p0.WrapperConnectionPoolDataSou
rce@e4b821d9 [ acquireIncrement -&gt; 5, acquireRetryAttempts -&gt; 0, acquireRetryDel
ay -&gt; 500, autoCommitOnClose -&gt; true, automaticTestTable -&gt; connection_test_tabl
e, breakAfterAcquireFailure -&gt; false, checkoutTimeout -&gt; 0, connectionCustomizer
ClassName -&gt; null, connectionTesterClassName -&gt; com.mchange.v2.c3p0.impl.Default
ConnectionTester, debugUnreturnedConnectionStackTraces -&gt; false, factoryClassLoc
ation -&gt; null, forceIgnoreUnresolvedTransactions -&gt; false, identityToken -&gt; 2rvx
tt7vbvtlhj13dgppf|82c01f, idleConnectionTestPeriod -&gt; 60, initialPoolSize -&gt; 3,
maxAdministrativeTaskTime -&gt; 0, maxConnectionAge -&gt; 0, maxIdleTime -&gt; 0, maxIdle
TimeExcessConnections -&gt; 0, maxPoolSize -&gt; 50, maxStatements -&gt; 0, maxStatements
PerConnection -&gt; 10, minPoolSize -&gt; 1, nestedDataSource -&gt; com.mchange.v2.c3p0.D
riverManagerDataSource@1a5f93f6 [ description -&gt; null, driverClass -&gt; null, fact
oryClassLocation -&gt; null, identityToken -&gt; 2rvxtt7vbvtlhj13dgppf|18ac738, jdbcUr
l -&gt; jdbc:mysql://localhost/459Server, properties -&gt; {user=******, password=****
**} ], preferredTestQuery -&gt; null, propertyCycle -&gt; 0, testConnectionOnCheckin -
&gt; true, testConnectionOnCheckout -&gt; false, unreturnedConnectionTimeout -&gt; 0, use
sTraditionalReflectiveProxies -&gt; false; userOverrides: {} ], dataSourceName -&gt; n
ull, factoryClassLocation -&gt; null, identityToken -&gt; 2rvxtt7vbvtlhj13dgppf|13bad1
2, numHelperThreads -&gt; 3 ]
com.mysql.jdbc.CommunicationsException: Communications link failure due to under
lying exception:

** BEGIN NESTED EXCEPTION **

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(Unknown Source)
        at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.&lt;init&gt;(Unknown Source)
        at java.net.Socket.&lt;init&gt;(Unknown Source)
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.ja
va:173)
        at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:267)
        at com.mysql.jdbc.Connection.createNewIO(Connection.java:2739)
        at com.mysql.jdbc.Connection.&lt;init&gt;(Connection.java:1553)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java
:266)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManag
erDataSource.java:120)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti
on(WrapperConnectionPoolDataSource.java:143)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti
on(WrapperConnectionPoolDataSource.java:132)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.initializeAu
tomaticTestTable(C3P0PooledConnectionPoolManager.java:772)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooled
ConnectionPool(C3P0PooledConnectionPoolManager.java:696)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0
PooledConnectionPoolManager.java:257)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0
PooledConnectionPoolManager.java:271)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(A
bstractPoolBackedDataSource.java:128)
        at net.cellkyborg.server.SQLHandler.&lt;init&gt;(SQLHandler.java:42)
        at net.cellkyborg.server.server.main(server.java:23)


** END NESTED EXCEPTION **



Last packet sent to the server was 0 ms ago.
        at com.mysql.jdbc.Connection.createNewIO(Connection.java:2814)
        at com.mysql.jdbc.Connection.&lt;init&gt;(Connection.java:1553)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java
:266)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManag
erDataSource.java:120)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti
on(WrapperConnectionPoolDataSource.java:143)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti
on(WrapperConnectionPoolDataSource.java:132)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.initializeAu
tomaticTestTable(C3P0PooledConnectionPoolManager.java:772)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooled
ConnectionPool(C3P0PooledConnectionPoolManager.java:696)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0
PooledConnectionPoolManager.java:257)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0
PooledConnectionPoolManager.java:271)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(A
bstractPoolBackedDataSource.java:128)
        at net.cellkyborg.server.SQLHandler.&lt;init&gt;(SQLHandler.java:42)
        at net.cellkyborg.server.server.main(server.java:23)
Login packet size: 124
109 173 66 29 250 164 76 26 125 161 149 98 139 66 233 103 166 168 238 72 174 192
 87 250 d00m is signing onto server. wizzy
Exception in thread &quot;Thread-9&quot; java.lang.NullPointerException
        at net.cellkyborg.server.SQLHandler.loadCharacter(SQLHandler.java:191)
        at net.cellkyborg.server.SQLHandler.readCharacter(SQLHandler.java:174)
        at net.cellkyborg.RSInstances.RSPlayer.run(RSPlayer.java:207)
        at java.lang.Thread.run(Unknown Source)
[/code]
Can somebody please help me,i put the titanscape(Cache) in the C: drive and that worked but i cant log in. :confused:
Can somebody please give me some advise on what to do?

~MoparUnited~</description>
    
    <lastBuildDate>Wed, 16 Jul 2008 12:38:22 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/can-somebody-please-help-me-on-this-error/220669.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Can somebody please help me on this error</title>
        <dc:creator><![CDATA[@MoparUnited MoparUnited]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/moparunited">@MoparUnited</a> wrote:</p>
          <blockquote>
              <p>I was running the 474 server than the client,than this error came up when i logged on with d00m</p>
<p>[code]16/07/2008 17:45:21 com.mchange.v2.log.MLog <br>
INFO: MLog clients using java 1.4+ standard logging.<br>
16/07/2008 17:45:22 com.mchange.v2.c3p0.C3P0Registry banner<br>
INFO: Initializing c3p0-0.9.1.1 [built 15-March-2007 01:32:31; debug? true; trac<br>
e: 10]<br>
16/07/2008 17:45:22 com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource getPoo<br>
lManager<br>
INFO: Initializing c3p0 pool… com.mchange.v2.c3p0.PoolBackedDataSource@22d9f7a<br>
5 [ connectionPoolDataSource -&gt; com.mchange.v2.c3p0.WrapperConnectionPoolDataSou<br>
rce@e4b821d9 [ acquireIncrement -&gt; 5, acquireRetryAttempts -&gt; 0, acquireRetryDel<br>
ay -&gt; 500, autoCommitOnClose -&gt; true, automaticTestTable -&gt; connection_test_tabl<br>
e, breakAfterAcquireFailure -&gt; false, checkoutTimeout -&gt; 0, connectionCustomizer<br>
ClassName -&gt; null, connectionTesterClassName -&gt; com.mchange.v2.c3p0.impl.Default<br>
ConnectionTester, debugUnreturnedConnectionStackTraces -&gt; false, factoryClassLoc<br>
ation -&gt; null, forceIgnoreUnresolvedTransactions -&gt; false, identityToken -&gt; 2rvx<br>
tt7vbvtlhj13dgppf|82c01f, idleConnectionTestPeriod -&gt; 60, initialPoolSize -&gt; 3,<br>
maxAdministrativeTaskTime -&gt; 0, maxConnectionAge -&gt; 0, maxIdleTime -&gt; 0, maxIdle<br>
TimeExcessConnections -&gt; 0, maxPoolSize -&gt; 50, maxStatements -&gt; 0, maxStatements<br>
PerConnection -&gt; 10, minPoolSize -&gt; 1, nestedDataSource -&gt; com.mchange.v2.c3p0.D<br>
riverManagerDataSource@1a5f93f6 [ description -&gt; null, driverClass -&gt; null, fact<br>
oryClassLocation -&gt; null, identityToken -&gt; 2rvxtt7vbvtlhj13dgppf|18ac738, jdbcUr<br>
l -&gt; jdbc:mysql://localhost/459Server, properties -&gt; {user=**<strong><strong>, password=</strong></strong><br>
**} ], preferredTestQuery -&gt; null, propertyCycle -&gt; 0, testConnectionOnCheckin -</p>
<blockquote>
<p>true, testConnectionOnCheckout -&gt; false, unreturnedConnectionTimeout -&gt; 0, use<br>
sTraditionalReflectiveProxies -&gt; false; userOverrides: {} ], dataSourceName -&gt; n<br>
ull, factoryClassLocation -&gt; null, identityToken -&gt; 2rvxtt7vbvtlhj13dgppf|13bad1<br>
2, numHelperThreads -&gt; 3 ]<br>
com.mysql.jdbc.CommunicationsException: Communications link failure due to under<br>
lying exception:</p>
</blockquote>
<p>** BEGIN NESTED EXCEPTION **</p>
<p>java.net.ConnectException<br>
MESSAGE: Connection refused: connect</p>
<p>STACKTRACE:</p>
<p>java.net.ConnectException: Connection refused: connect<br>
at java.net.PlainSocketImpl.socketConnect(Native Method)<br>
at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
at java.net.PlainSocketImpl.connectToAddress(Unknown Source)<br>
at java.net.PlainSocketImpl.connect(Unknown Source)<br>
at java.net.SocksSocketImpl.connect(Unknown Source)<br>
at java.net.Socket.connect(Unknown Source)<br>
at java.net.Socket.connect(Unknown Source)<br>
at java.net.Socket.(Unknown Source)<br>
at java.net.Socket.(Unknown Source)<br>
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.ja<br>
va:173)<br>
at com.mysql.jdbc.MysqlIO.(MysqlIO.java:267)<br>
at com.mysql.jdbc.Connection.createNewIO(Connection.java:2739)<br>
at com.mysql.jdbc.Connection.(Connection.java:1553)<br>
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java<br>
:266)<br>
at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManag<br>
erDataSource.java:120)<br>
at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti<br>
on(WrapperConnectionPoolDataSource.java:143)<br>
at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti<br>
on(WrapperConnectionPoolDataSource.java:132)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.initializeAu<br>
tomaticTestTable(C3P0PooledConnectionPoolManager.java:772)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooled<br>
ConnectionPool(C3P0PooledConnectionPoolManager.java:696)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0<br>
PooledConnectionPoolManager.java:257)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0<br>
PooledConnectionPoolManager.java:271)<br>
at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(A<br>
bstractPoolBackedDataSource.java:128)<br>
at net.cellkyborg.server.SQLHandler.(SQLHandler.java:42)<br>
at net.cellkyborg.server.server.main(server.java:23)</p>
<p>** END NESTED EXCEPTION **</p>
<p>Last packet sent to the server was 0 ms ago.<br>
at com.mysql.jdbc.Connection.createNewIO(Connection.java:2814)<br>
at com.mysql.jdbc.Connection.(Connection.java:1553)<br>
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java<br>
:266)<br>
at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManag<br>
erDataSource.java:120)<br>
at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti<br>
on(WrapperConnectionPoolDataSource.java:143)<br>
at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnecti<br>
on(WrapperConnectionPoolDataSource.java:132)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.initializeAu<br>
tomaticTestTable(C3P0PooledConnectionPoolManager.java:772)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooled<br>
ConnectionPool(C3P0PooledConnectionPoolManager.java:696)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0<br>
PooledConnectionPoolManager.java:257)<br>
at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0<br>
PooledConnectionPoolManager.java:271)<br>
at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(A<br>
bstractPoolBackedDataSource.java:128)<br>
at net.cellkyborg.server.SQLHandler.(SQLHandler.java:42)<br>
at net.cellkyborg.server.server.main(server.java:23)<br>
Login packet size: 124<br>
109 173 66 29 250 164 76 26 125 161 149 98 139 66 233 103 166 168 238 72 174 192<br>
87 250 d00m is signing onto server. wizzy<br>
Exception in thread “Thread-9” java.lang.NullPointerException<br>
at net.cellkyborg.server.SQLHandler.loadCharacter(SQLHandler.java:191)<br>
at net.cellkyborg.server.SQLHandler.readCharacter(SQLHandler.java:174)<br>
at net.cellkyborg.RSInstances.RSPlayer.run(RSPlayer.java:207)<br>
at java.lang.Thread.run(Unknown Source)<br>
[/code]<br>
Can somebody please help me,i put the titanscape(Cache) in the C: drive and that worked but i cant log in. <img src="https://forum.moparisthebest.com/images/emoji/twitter/confused.png?v=6" title=":confused:" class="emoji" alt=":confused:"><br>
Can somebody please give me some advise on what to do?</p>
<p>~MoparUnited~</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/can-somebody-please-help-me-on-this-error/220669/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/can-somebody-please-help-me-on-this-error/220669/1</link>
        <pubDate>Wed, 16 Jul 2008 12:38:22 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-220669-1</guid>
        <source url="https://forum.moparisthebest.com/t/can-somebody-please-help-me-on-this-error/220669.rss">Can somebody please help me on this error</source>
      </item>
  </channel>
</rss>
