<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Need Help With Running The Client</title>
    <link>https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121</link>
    <description>Okay guys so whenever i run my run.bat file on the source its fine but when i go on the client run.bat it shows the .jar file then a message pops up saying:
[code]Please Screenshot this message and send it to an Owner!

java.io.FileNotFoundException &quot;http://rs-virtue.net/cacheVersion.txt
sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknow Source)
java.net.URL.openStream(Unknown Source)
UpdateCache.egtNewestVersion(UpdateCache.java:34)
UpdateCache.run(RSApplet.java:33)
client.run(client.java:5112)
java.lang.Thread.run(Unknown Source)[/code]

and in the cmd for the source side side it shows this :
[code]va:579)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:19)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:40)
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,371,568,508,563 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/18/13 8:15 AM]:      ... 12 more
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met
hod)
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS
tackPlainSocketImpl.java:69)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl
ainSocketImpl.java:339)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs
tractPlainSocketImpl.java:200)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai
nSocketImpl.java:182)
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java
:157)
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java
:391)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:425)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:241)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/18/13 8:15 AM]:      ... 13 more
[6/18/13 8:15 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,371,568,511,495 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:19)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:40)
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,371,568,511,495 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/18/13 8:15 AM]:      ... 12 more
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met
hod)
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS
tackPlainSocketImpl.java:69)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl
ainSocketImpl.java:339)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs
tractPlainSocketImpl.java:200)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai
nSocketImpl.java:182)
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java
:157)
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java
:391)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:425)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:241)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/18/13 8:15 AM]:      ... 13 more
[6/18/13 8:15 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,371,568,514,458 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:19)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:40)
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,371,568,514,458 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/18/13 8:15 AM]:      ... 12 more
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met
hod)
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS
tackPlainSocketImpl.java:69)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl
ainSocketImpl.java:339)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs
tractPlainSocketImpl.java:200)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai
nSocketImpl.java:182)
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java
:157)
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java
:391)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:425)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:241)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/18/13 8:15 AM]:      ... 13 more
[6/18/13 8:15 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,371,568,517,414 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:19)
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:40)
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,371,568,517,414 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[6/18/13 8:15 AM]:      ... 12 more
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met
hod)
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS
tackPlainSocketImpl.java:69)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl
ainSocketImpl.java:339)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs
tractPlainSocketImpl.java:200)
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai
nSocketImpl.java:182)
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java
:157)
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java
:391)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:425)
[6/18/13 8:15 AM]:      at java.net.Socket.&lt;init&gt;(Socket.java:241)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[6/18/13 8:15 AM]:      ... 13 more
[/code]</description>
    
    <lastBuildDate>Tue, 18 Jun 2013 15:43:15 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Need Help With Running The Client</title>
        <dc:creator><![CDATA[@yo_its_jake yo its jake]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/yo_its_jake">@yo_its_jake</a> wrote:</p>
          <blockquote>
              <p>Niex pmed you my Teamviewer stuff</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121/3">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121/3</link>
        <pubDate>Tue, 18 Jun 2013 15:43:15 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-522121-3</guid>
        <source url="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121.rss">Need Help With Running The Client</source>
      </item>
      <item>
        <title>Need Help With Running The Client</title>
        <dc:creator><![CDATA[@NieX NieX]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/niex">@NieX</a> wrote:</p>
          <blockquote>
              <p>skype? ill tv.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121/2</link>
        <pubDate>Tue, 18 Jun 2013 15:37:27 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-522121-2</guid>
        <source url="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121.rss">Need Help With Running The Client</source>
      </item>
      <item>
        <title>Need Help With Running The Client</title>
        <dc:creator><![CDATA[@yo_its_jake yo its jake]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/yo_its_jake">@yo_its_jake</a> wrote:</p>
          <blockquote>
              <p>Okay guys so whenever i run my run.bat file on the source its fine but when i go on the client run.bat it shows the .jar file then a message pops up saying:</p>
<p>[code]Please Screenshot this message and send it to an Owner!</p>
<p>java.io.FileNotFoundException "<a href="http://rs-virtue.net/cacheVersion.txt" rel="nofollow noopener">http://rs-virtue.net/cacheVersion.txt</a><br>
sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknow Source)<br>
java.net.URL.openStream(Unknown Source)<br>
UpdateCache.egtNewestVersion(UpdateCache.java:34)<br>
UpdateCache.run(RSApplet.java:33)<br>
client.run(client.java:5112)<br>
java.lang.Thread.run(Unknown Source)[/code]</p>
<p>and in the cmd for the source side side it shows this :</p>
<p>[code]va:579)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:19)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:40)<br>
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,508,563 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/18/13 8:15 AM]:      … 12 more<br>
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met<br>
hod)<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS<br>
tackPlainSocketImpl.java:69)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl<br>
ainSocketImpl.java:339)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs<br>
tractPlainSocketImpl.java:200)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai<br>
nSocketImpl.java:182)<br>
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java<br>
:157)<br>
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java<br>
:391)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:425)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:241)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/18/13 8:15 AM]:      … 13 more<br>
[6/18/13 8:15 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,511,495 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:19)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:40)<br>
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,511,495 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/18/13 8:15 AM]:      … 12 more<br>
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met<br>
hod)<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS<br>
tackPlainSocketImpl.java:69)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl<br>
ainSocketImpl.java:339)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs<br>
tractPlainSocketImpl.java:200)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai<br>
nSocketImpl.java:182)<br>
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java<br>
:157)<br>
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java<br>
:391)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:425)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:241)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/18/13 8:15 AM]:      … 13 more<br>
[6/18/13 8:15 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,514,458 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:19)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:40)<br>
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,514,458 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/18/13 8:15 AM]:      … 12 more<br>
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met<br>
hod)<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS<br>
tackPlainSocketImpl.java:69)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl<br>
ainSocketImpl.java:339)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs<br>
tractPlainSocketImpl.java:200)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai<br>
nSocketImpl.java:182)<br>
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java<br>
:157)<br>
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java<br>
:391)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:425)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:241)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/18/13 8:15 AM]:      … 13 more<br>
[6/18/13 8:15 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,517,414 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[6/18/13 8:15 AM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:19)<br>
[6/18/13 8:15 AM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:40)<br>
[6/18/13 8:15 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,371,568,517,414 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[6/18/13 8:15 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[6/18/13 8:15 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[6/18/13 8:15 AM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[6/18/13 8:15 AM]:      … 12 more<br>
[6/18/13 8:15 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.connect0(Native Met<br>
hod)<br>
[6/18/13 8:15 AM]:      at java.net.DualStackPlainSocketImpl.socketConnect(DualS<br>
tackPlainSocketImpl.java:69)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPl<br>
ainSocketImpl.java:339)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connectToAddress(Abs<br>
tractPlainSocketImpl.java:200)<br>
[6/18/13 8:15 AM]:      at java.net.AbstractPlainSocketImpl.connect(AbstractPlai<br>
nSocketImpl.java:182)<br>
[6/18/13 8:15 AM]:      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java<br>
:157)<br>
[6/18/13 8:15 AM]:      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java<br>
:391)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:579)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.connect(Socket.java:528)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:425)<br>
[6/18/13 8:15 AM]:      at java.net.Socket.(Socket.java:241)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[6/18/13 8:15 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[6/18/13 8:15 AM]:      … 13 more<br>
[/code]</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121/1</link>
        <pubDate>Tue, 18 Jun 2013 15:15:51 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-522121-1</guid>
        <source url="https://forum.moparisthebest.com/t/need-help-with-running-the-client/522121.rss">Need Help With Running The Client</source>
      </item>
  </channel>
</rss>
