<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>[317] Socket Exception</title>
    <link>https://forum.moparisthebest.com/t/317-socket-exception/336608</link>
    <description>Hi, I&#39;ve been working on a Winterlove-based source and when I log out, I get this error:

[code=java]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
        at ClientHandler.run(ClientHandler.java:612)
        at java.lang.Thread.run(Thread.java:619)
[/code]

It&#39;s an error stating the program is still trying to write after the connection was broken. The exact line that&#39;s causing the error is:

[code=java]out.write(buffer, offset, numBytesInBuffer);[/code]

But I can&#39;t figure out how to fix it, any ideas?

Seething</description>
    
    <lastBuildDate>Mon, 12 Apr 2010 11:44:28 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/317-socket-exception/336608.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>[317] Socket Exception</title>
        <dc:creator><![CDATA[@Seething Seething]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/seething">@Seething</a> wrote:</p>
          <blockquote>
              <p>Hi, I’ve been working on a Winterlove-based source and when I log out, I get this error:</p>
<pre><code class="lang-auto">java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
        at ClientHandler.run(ClientHandler.java:612)
        at java.lang.Thread.run(Thread.java:619)</code></pre>
<p>It’s an error stating the program is still trying to write after the connection was broken. The exact line that’s causing the error is:</p>
<pre><code class="lang-auto">out.write(buffer, offset, numBytesInBuffer);</code></pre>
<p>But I can’t figure out how to fix it, any ideas?</p>
<p>Seething</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/317-socket-exception/336608/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/317-socket-exception/336608/1</link>
        <pubDate>Mon, 12 Apr 2010 11:44:28 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-336608-1</guid>
        <source url="https://forum.moparisthebest.com/t/317-socket-exception/336608.rss">[317] Socket Exception</source>
      </item>
  </channel>
</rss>
