<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Weird Error - Much Thanks</title>
    <link>https://forum.moparisthebest.com/t/weird-error-much-thanks/374742</link>
    <description>Hello, I get this error when I start my server. It is PI source. I added a few snippets, but couldn&#39;t see relation of this error to them. I added, chat logs.

Here is the error, much thanks!

[CODE][12/23/10 7:45 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Com
munications link failure

The last packet successfully received from the server was 1,293,149,739,604 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[12/23/10 7:45 PM]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[12/23/10 7:45 PM]:     at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[12/23/10 7:45 PM]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[12/23/10 7:45 PM]:     at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[12/23/10 7:45 PM]:     at java.sql.DriverManager.getConnection(Unknown Source)
[12/23/10 7:45 PM]:     at java.sql.DriverManager.getConnection(Unknown Source)
[12/23/10 7:45 PM]:     at server.util.SQL.createConnection(SQL.java:17)
[12/23/10 7:45 PM]:     at server.Server.main(Server.java:104)
[12/23/10 7:45 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExc
eption: Communications link failure

The last packet successfully received from the server was 1,293,149,739,604 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[12/23/10 7:45 PM]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[12/23/10 7:45 PM]:     at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[12/23/10 7:45 PM]:     ... 13 more
[12/23/10 7:45 PM]: Caused by: java.net.ConnectException: Connection refused: co
nnect
[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.socketConnect(Native Method)

[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.doConnect(Unknown Source)
[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.connectToAddress(Unknown Sou
rce)
[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.connect(Unknown Source)
[12/23/10 7:45 PM]:     at java.net.SocksSocketImpl.connect(Unknown Source)
[12/23/10 7:45 PM]:     at java.net.Socket.connect(Unknown Source)
[12/23/10 7:45 PM]:     at java.net.Socket.connect(Unknown Source)
[12/23/10 7:45 PM]:     at java.net.Socket.&lt;init&gt;(Unknown Source)
[12/23/10 7:45 PM]:     at java.net.Socket.&lt;init&gt;(Unknown Source)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[12/23/10 7:45 PM]:     at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[12/23/10 7:45 PM]:     ... 14 more[/CODE]</description>
    
    <lastBuildDate>Fri, 24 Dec 2010 00:27:25 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Weird Error - Much Thanks</title>
        <dc:creator><![CDATA[@James-RevolutionX James-RevolutionX]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/james-revolutionx">@James-RevolutionX</a> wrote:</p>
          <blockquote>
              <p>Your link for the MYSQL to connect is failed, maybe a wrong domain or site.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742/3">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/weird-error-much-thanks/374742/3</link>
        <pubDate>Fri, 24 Dec 2010 00:27:25 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-374742-3</guid>
        <source url="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742.rss">Weird Error - Much Thanks</source>
      </item>
      <item>
        <title>Weird Error - Much Thanks</title>
        <dc:creator><![CDATA[@Sir_Jay Sir Jay]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/sir_jay">@Sir_Jay</a> wrote:</p>
          <blockquote>
              <p>Cannot connect to the mysql data base:</p>
<blockquote>Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
Caused by: java.net.ConnectException: Connection refused: connect</blockquote>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/weird-error-much-thanks/374742/2</link>
        <pubDate>Fri, 24 Dec 2010 00:25:39 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-374742-2</guid>
        <source url="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742.rss">Weird Error - Much Thanks</source>
      </item>
      <item>
        <title>Weird Error - Much Thanks</title>
        <dc:creator><![CDATA[@360236 360236]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/360236">@360236</a> wrote:</p>
          <blockquote>
              <p>Hello, I get this error when I start my server. It is PI source. I added a few snippets, but couldnâ€™t see relation of this error to them. I added, chat logs.</p>
<p>Here is the error, much thanks!</p>
<p>[CODE][12/23/10 7:45 PM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Com<br>
munications link failure</p>
<p>The last packet successfully received from the server was 1,293,149,739,604 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[12/23/10 7:45 PM]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[12/23/10 7:45 PM]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[12/23/10 7:45 PM]:     at java.sql.DriverManager.getConnection(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.sql.DriverManager.getConnection(Unknown Source)<br>
[12/23/10 7:45 PM]:     at server.util.SQL.createConnection(SQL.java:17)<br>
[12/23/10 7:45 PM]:     at server.Server.main(Server.java:104)<br>
[12/23/10 7:45 PM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExc<br>
eption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,293,149,739,604 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[12/23/10 7:45 PM]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[12/23/10 7:45 PM]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[12/23/10 7:45 PM]:     â€¦ 13 more<br>
[12/23/10 7:45 PM]: Caused by: java.net.ConnectException: Connection refused: co<br>
nnect<br>
[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[12/23/10 7:45 PM]:     at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.net.Socket.connect(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.net.Socket.connect(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.net.Socket.(Unknown Source)<br>
[12/23/10 7:45 PM]:     at java.net.Socket.(Unknown Source)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[12/23/10 7:45 PM]:     at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[12/23/10 7:45 PM]:     â€¦ 14 more[/CODE]</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/weird-error-much-thanks/374742/1</link>
        <pubDate>Fri, 24 Dec 2010 00:21:28 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-374742-1</guid>
        <source url="https://forum.moparisthebest.com/t/weird-error-much-thanks/374742.rss">Weird Error - Much Thanks</source>
      </item>
  </channel>
</rss>
