<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Weird? Really need some help</title>
    <link>https://forum.moparisthebest.com/t/weird-really-need-some-help/452473</link>
    <description>Alright this a really weird problem. So I just added martins auto donation system http://www.rune-server.org/runescape-development/rs2-server/tutorials/323057-martins-auto-donation-system.html it works perfectly but when I run my source I get all these messages it still works just want to get rid of them because I believe they cause lag.

[code=java][2/08/12 3:37 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:37 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:37 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:37 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:37 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:37 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:37 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:37 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:37 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:37 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:38 PM]: Average Cycle Time: 16ms
[2/08/12 3:38 PM]: Players online: 1, engine load: 3.38%
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user &#39;username&#39;@&#39;loc
alhost&#39; (using password: YES)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:1055)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j
ava:956)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3536)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3468)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
917)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397
4)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)

[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2142)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor
.java:525)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:579)
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja
va:221)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT
urnipConnection.java:14)
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti
on.java:31)
[/code]</description>
    
    <lastBuildDate>Thu, 02 Aug 2012 03:39:22 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/weird-really-need-some-help/452473.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Weird? Really need some help</title>
        <dc:creator><![CDATA[@ClairtyX ClairtyX]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/clairtyx">@ClairtyX</a> wrote:</p>
          <blockquote>
              <p>Alright this a really weird problem. So I just added martins auto donation system <a href="http://www.rune-server.org/runescape-development/rs2-server/tutorials/323057-martins-auto-donation-system.html" rel="nofollow noopener">http://www.rune-server.org/runescape-development/rs2-server/tutorials/323057-martins-auto-donation-system.html</a> it works perfectly but when I run my source I get all these messages it still works just want to get rid of them because I believe they cause lag.</p>
<p>[code=java][2/08/12 3:37 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:37 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:37 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:37 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:37 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:37 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:37 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:37 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:37 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:37 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:37 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:37 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:38 PM]: Average Cycle Time: 16ms<br>
[2/08/12 3:38 PM]: Players online: 1, engine load: 3.38%<br>
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[2/08/12 3:38 PM]: java.sql.SQLException: Access denied for user ‘username’@‘loc<br>
alhost’ (using password: YES)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:1055)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.SQLError.createSQLException(SQLError.j<br>
ava:956)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3536)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
3468)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:<br>
917)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:397<br>
4)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1282)</p>
<p>[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2142)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[2/08/12 3:38 PM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[2/08/12 3:38 PM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(DelegatingConstructorAccessorImpl.java:45)<br>
[2/08/12 3:38 PM]:      at java.lang.reflect.Constructor.newInstance(Constructor<br>
.java:525)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[2/08/12 3:38 PM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:579)<br>
[2/08/12 3:38 PM]:      at java.sql.DriverManager.getConnection(DriverManager.ja<br>
va:221)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.createConnection(MadT<br>
urnipConnection.java:14)<br>
[2/08/12 3:38 PM]:      at server.util.MadTurnipConnection.run(MadTurnipConnecti<br>
on.java:31)<br>
[/code]</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/weird-really-need-some-help/452473/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/weird-really-need-some-help/452473/1</link>
        <pubDate>Thu, 02 Aug 2012 03:39:22 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-452473-1</guid>
        <source url="https://forum.moparisthebest.com/t/weird-really-need-some-help/452473.rss">Weird? Really need some help</source>
      </item>
  </channel>
</rss>
