<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>[639] Dementhium - Damage Error</title>
    <link>https://forum.moparisthebest.com/t/639-dementhium-damage-error/537284</link>
    <description>For some reason in my server if im fighting an npc, if I use the steel titan&#39;s special move as the last hit I get this error in the server cmd prompt:
[CODE]
[ActionButtonHandler] interfaceId=548 buttonId=132 slot=-1 itemId=-1
[CastAttackHandler] 17, 747, 0, 1335, false, 65535
[CastAttackHandler] 17, 747, 0, 1335, false, 65535
java.lang.NullPointerException
        at org.dementhium.model.npc.NPC.sendDead(NPC.java:270)
        at org.dementhium.model.npc.NPC.hit(NPC.java:187)
        at org.dementhium.model.misc.DamageManager.updateDamageAttributes(Damage
Manager.java:325)
        at org.dementhium.model.misc.DamageManager.damage(DamageManager.java:290
)
        at org.dementhium.model.misc.DamageManager.damage(DamageManager.java:271
)
        at org.dementhium.model.combat.impl.npc.SteelTitanAction.endSession(Stee
lTitanAction.java:193)
        at org.dementhium.model.combat.CombatAction.execute(CombatAction.java:59
)
        at org.dementhium.model.combat.CombatExecutor$1.run(CombatExecutor.java:
109)
        at org.dementhium.model.combat.CombatExecutor.tick(CombatExecutor.java:1
24)
        at org.dementhium.task.impl.NPCTickTask.execute(NPCTickTask.java:25)
        at org.dementhium.task.SequentialTaskExecutor.performTasks(SequentialTas
kExecutor.java:13)
        at org.dementhium.model.World.run(World.java:184)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java
:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:603)
        at java.lang.Thread.run(Thread.java:722)
[CastAttackHandler] 17, 747, 0, 1335, false, 65535
[/CODE]

I&#39;ll try and explain what happens:
There are no errors when the special move for the steel titan is cast during combat, it damages the npc no errors. However if the move is used and it KILLS the npc(Aka the final hit) I get that error, and the npc doesn&#39;t die. The npc no longer engages in combat, and cannot be attacked. It just sits there, never respawning and never dying. 
I believe this has somethin to do with DamageManager.java but im not sure how I would fix this?
I will be forever grateful for any help!</description>
    
    <lastBuildDate>Thu, 19 Dec 2013 23:20:54 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/639-dementhium-damage-error/537284.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>[639] Dementhium - Damage Error</title>
        <dc:creator><![CDATA[@99rangek0 99rangek0]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/99rangek0">@99rangek0</a> wrote:</p>
          <blockquote>
              <p>For some reason in my server if im fighting an npc, if I use the steel titan’s special move as the last hit I get this error in the server cmd prompt:</p>
<p><code>
[ActionButtonHandler] interfaceId=548 buttonId=132 slot=-1 itemId=-1
[CastAttackHandler] 17, 747, 0, 1335, false, 65535
[CastAttackHandler] 17, 747, 0, 1335, false, 65535
java.lang.NullPointerException
        at org.dementhium.model.npc.NPC.sendDead(NPC.java:270)
        at org.dementhium.model.npc.NPC.hit(NPC.java:187)
        at org.dementhium.model.misc.DamageManager.updateDamageAttributes(Damage
Manager.java:325)
        at org.dementhium.model.misc.DamageManager.damage(DamageManager.java:290
)
        at org.dementhium.model.misc.DamageManager.damage(DamageManager.java:271
)
        at org.dementhium.model.combat.impl.npc.SteelTitanAction.endSession(Stee
lTitanAction.java:193)
        at org.dementhium.model.combat.CombatAction.execute(CombatAction.java:59
)
        at org.dementhium.model.combat.CombatExecutor$1.run(CombatExecutor.java:
109)
        at org.dementhium.model.combat.CombatExecutor.tick(CombatExecutor.java:1
24)
        at org.dementhium.task.impl.NPCTickTask.execute(NPCTickTask.java:25)
        at org.dementhium.task.SequentialTaskExecutor.performTasks(SequentialTas
kExecutor.java:13)
        at org.dementhium.model.World.run(World.java:184)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java
:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:603)
        at java.lang.Thread.run(Thread.java:722)
[CastAttackHandler] 17, 747, 0, 1335, false, 65535
</code></p>
<p>I’ll try and explain what happens:<br>
There are no errors when the special move for the steel titan is cast during combat, it damages the npc no errors. However if the move is used and it KILLS the npc(Aka the final hit) I get that error, and the npc doesn’t die. The npc no longer engages in combat, and cannot be attacked. It just sits there, never respawning and never dying.<br>
I believe this has somethin to do with DamageManager.java but im not sure how I would fix this?<br>
I will be forever grateful for any help!</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/639-dementhium-damage-error/537284/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/639-dementhium-damage-error/537284/1</link>
        <pubDate>Thu, 19 Dec 2013 23:20:54 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-537284-1</guid>
        <source url="https://forum.moparisthebest.com/t/639-dementhium-damage-error/537284.rss">[639] Dementhium - Damage Error</source>
      </item>
  </channel>
</rss>
